#	vsFTPd container's Dockerfile

# Installing FTP image (5M uploads)
FROM bogem/ftp

# Installing debugging tools
# RUN  apt-get install -y procps nano mc nmap

# Instructions for Docker that the container is listening on port 6379
# (by default TCP protocol)
EXPOSE 20 21 47400-47470:47400-47470
